### ISSUE TITLE
Function concern: stewicombo.combineInventoriesforFacilityList

### ISSUE THREAD

**Issue by jeff-ball** [USEPA/standardizedinventories#167]
**I have tried multiple times to use this function to extract the inventory data for specific facilities by using the FRS ID. I have used different versions of the stewi package and created a virtual environment to download the necessary packages with the correct versions based on the setup.py file. Nevertheless, I still got errors when executing the function:** 

``` 
import stewi
import stewicombo 

combined_data = stewicombo.combineInventoriesforFacilityList('TRI', 
                                                             { 'NEI': 2019, 'TRI': 2019}, ['110070028687' '110069500604' '110050297936'],
                                                               filter_for_LCI=True, remove_overlap=True, keep_sec_cntx=False)
``` 

_**This is the output in my terminal:**_

INFO Returning /Users/jab/Library/Application Support/facilitymatcher/FacilityMatchList_forStEWI_v1.1.3.parquet
INFO Returning /Users/jab/Library/Application Support/stewi/flowbyfacility/NEI_2019_v1.1.0.parquet
INFO loaded NEI_2019 from /Users/jab/Library/Application Support/stewi/flowbyfacility
INFO filtering for US states
INFO Returning /Users/jab/Library/Application Support/stewi/facility/NEI_2019_v1.1.0.parquet
INFO loaded NEI_2019 from /Users/jab/Library/Application Support/stewi/facility
INFO removing flows not relevant for LCI
INFO TRI_2019 not found in /Users/jab/Library/Application Support/stewi/flowbyfacility
INFO requested inventory does not exist in local directory, it will be generated...
INFO downloading TRI files from source for 2019
INFO US_1a_2019.csv saved to /Users/jab/Library/Application Support/stewi/TRI Data Files
INFO US_3a_2019.csv saved to /Users/jab/Library/Application Support/stewi/TRI Data Files
INFO generating TRI inventory from files for 2019
INFO GeoPandas and/or Shapely were not successfully imported,
so esupy.context_secondary is unable to assign an urban/rural compartment.
 See esupy/README.md for install instructions.
INFO saving TRI_2019 to /Users/jab/Library/Application Support/stewi/facility
INFO validating data against national totals
WARNING 19 potential issues in validation exceeding tolerance
INFO writing validation result to /Users/jab/Library/Application Support/stewi/validation
INFO saving TRI_2019 to /Users/jab/Library/Application Support/stewi/flow
INFO saving TRI_2019 to /Users/jab/Library/Application Support/stewi/flowbyfacility
INFO Returning /Users/jab/Library/Application Support/stewi/flowbyfacility/TRI_2019_v1.1.0.parquet
INFO loaded TRI_2019 from /Users/jab/Library/Application Support/stewi/flowbyfacility
INFO filtering for US states
INFO Returning /Users/jab/Library/Application Support/stewi/facility/TRI_2019_v1.1.0.parquet
INFO loaded TRI_2019 from /Users/jab/Library/Application Support/stewi/facility
INFO removing flows not relevant for LCI
INFO removing overlap between inventories
Traceback (most recent call last):
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '_SourcePref'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/pandas/core/frame.py", line 3746, in _set_item_mgr
    loc = self._info_axis.get_loc(key)
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: '_SourcePref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jab/Library/CloudStorage/OneDrive-ArizonaStateUniversity/ASU Research/Project 1/US Model/Code files/Test.py", line 46, in <module>
    combined_data = stewicombo.combineInventoriesforFacilityList('TRI', 
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/stewicombo/__init__.py", line 134, in combineInventoriesforFacilityList
    inventories = aggregate_and_remove_overlap(inventories)
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/stewicombo/overlaphandler.py", line 143, in aggregate_and_remove_overlap
    df_dup['_SourcePref'] = df_dup.apply(
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/pandas/core/frame.py", line 3599, in __setitem__
    self._set_item_frame_value(key, value)
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/pandas/core/frame.py", line 3737, in _set_item_frame_value
    self._set_item_mgr(key, arraylike)
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/pandas/core/frame.py", line 3749, in _set_item_mgr
    self._mgr.insert(len(self._info_axis), key, value)
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1155, in insert
    block = new_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 1922, in new_block
    check_ndim(values, placement, ndim)
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 1964, in check_ndim
    raise ValueError(
ValueError: Wrong number of items passed 12, placement implies 1

**Comment by bl-young** [comment]
thanks I will review

**Comment by jeff-ball** [comment]
Please, let me know if I should do something from my side. This is very important for my current research project. I will always keep an eye and learn more about the structure of the current python package and its functions... 

Thank you!

**Comment by bl-young** [comment]
hi @jeff-ball - there is no data found for this query, because your list of facilities needs to be separated by a comma.

But once I fix that issue, the IDs you have passed appear to be FRS IDs? For this function, you need to pass the IDs from your `base_inventory` (e.g. TRI):
https://github.com/USEPA/standardizedinventories/blob/6710a0faf8a0ea74ad52747672a7a8998d369af3/stewicombo/__init__.py#L115-L116

**Comment by jeff-ball** [comment]
Hello @bl-young  - I noticed that yesterday night when I was checking another function with similar application. I have managed to combine the inventories for TRI, DMR, and NEI. This was of great help! Thank you for your support and efforts to grow this tool!

----

Another issue might be also the stewi package is not able to access data from both GHGRP and RCRAInfo databases. For instance running the following code will result in this error: 
`stewi.getInventory('GHGRP', '2019')
` 
INFO GHGRP_2019 not found in /Users/jab/Library/Application Support/stewi/flowbyfacility
INFO requested inventory does not exist in local directory, it will be generated...
INFO downloading and processing GHGRP data to /Users/jab/Library/Application Support/stewi/GHGRP Data Files/tables/2019
Traceback (most recent call last):
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/stewi/GHGRP.py", line 125, in get_row_count
    table_count = int(table_count[0].firstChild.nodeValue)
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
    hi = stewi.getInventory('GHGRP','2019')
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/stewi/__init__.py", line 82, in getInventory
    inventory = read_inventory(inventory_acronym, year, f,
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/stewi/globals.py", line 331, in read_inventory
    generate_inventory(inventory_acronym, year)
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/stewi/globals.py", line 365, in generate_inventory
    GHGRP.main(Option = 'A', Year = [year])
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/stewi/GHGRP.py", line 722, in main
    ghgrp1 = download_and_parse_subpart_tables(year, m)
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/stewi/GHGRP.py", line 295, in download_and_parse_subpart_tables
    table_df = import_or_download_table(filepath, subpart_emissions_table,
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/stewi/GHGRP.py", line 242, in import_or_download_table
    row_count = get_row_count(table, report_year=year)
  File "/Users/jab/stewi_env/lib/python3.9/site-packages/stewi/GHGRP.py", line 127, in get_row_count
    raise Exception(f'error accessing table count for {table}') from e
Exception: error accessing table count for C_CONFIGURATION_LEVEL_INFO

----
In the case of RCRAInfo, the data is accessed using a web manager as I learned. I have downloaded the required packages in my virtual environment, but I still had some issues and the data was never saved in the application support folder.

**Comment by bl-young** [comment]
I recommend using `download_if_missing=True` for all datasets to use pre-processed ones if possible, especially if you are having issues.

**Comment by jeff-ball** [comment]
> I recommend using download_if_missing=True for all datasets to use pre-processed ones if possible, especially if you are having issues.

Great! I used this. It works for the stewi.getInvenotry. When using stewicombo functions, I get the same errors again. 

1. GHGRP database:  _error accessing table count for C_CONFIGURATION_LEVEL_INFO_
2. RCRAInfo database: _TypeError: __init__() got multiple values for argument 'options'_

---- 

I will try to write a code to analyze the mentioned inventories, RCRAInfo and GHGRP, separately through stewi. Then, I can add them to my combined database because these two don't have overlap with NEI, TRI, or DMR. 


Thank you again! I'll let you know if it works and will share the code script.

**Comment by bl-young** [comment]
What year are you trying to access data for? It shouldn't try to regenerate GHGRP and RCRA data if you are using `download_if_missing=True`.

**Comment by jeff-ball** [comment]
> What year are you trying to access data for? It shouldn't try to regenerate GHGRP and RCRA data if you are using `download_if_missing=True`.

I am trying to generate a combined inventory for all databases through the tool, instead of doing it manually. I have specific facilities in mind; the inventory will help me collect all the related flows from the 5 databases. Thank you for the feedback!
