### ISSUE TITLE
[TRI] TRI -A download breaking

### ISSUE THREAD

**Issue by michael-long88** [USEPA/standardizedinventories#84]
Tried downloading some TRI data, but ran into the same issue for both 2016 and 2017
```
➜ python -m stewi.TRI A -Y 2016
INFO downloading TRI files from source for 2016
Traceback (most recent call last):
  File "/Users/michaellong/miniconda/envs/epa/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/michaellong/miniconda/envs/epa/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/michaellong/miniconda/envs/epa/lib/python3.8/site-packages/stewi/TRI.py", line 413, in <module>
    extract_TRI_data_files(link_zip_TRI, TRIFiles, TRIyear)
  File "/Users/michaellong/miniconda/envs/epa/lib/python3.8/site-packages/stewi/TRI.py", line 76, in extract_TRI_data_files
    for line in txtfile:
  File "/Users/michaellong/miniconda/envs/epa/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 153: invalid start byte
```

**Comment by bl-young** [comment]
ok I can't recreate this error. perhaps there is a dependency issue here. Can you confirm what version of pandas you have?

I will look into it

**Comment by michael-long88** [comment]
pandas version `1.3.1`

**Comment by bl-young** [comment]
@WesIngwersen @catherinebirney any chance you could try running the TRI module (with option A) to see if you can recreate this error?
perhaps ignoring or replacing the errors when reading the zip file but I dont want to lose too much data:
line 74:
```
with io.TextIOWrapper(z.open(filename + '.txt',
        mode='r'), errors='replace') as txtfile:
```

**Comment by WesIngwersen** [comment]
I can't replicate the error.  I'm using Python 3.7.2 and pandas 1.1.3
```
C:\Users\wesle\standardizedinventories>python -m stewi.TRI A -Y 2016
INFO downloading TRI files from source for 2016
INFO US_1a_2016.csv saved to C:\Users\wesle\AppData\Local\stewi/TRI Data Files/
INFO US_3a_2016.csv saved to C:\Users\wesle\AppData\Local\stewi/TRI Data Files/
```

**Comment by catherinebirney** [comment]
Also can't replicate the error. I get the same results as Wes.

Python 3.7 and pandas 1.2.3

**Comment by michael-long88** [comment]
That looks like it worked. After installing again, it doesn't look like `stewi/filter.yaml` got copied in though. After manually creating the file and copying in the yaml file contents, the TRI command ran perfectly.

**Comment by bl-young** [comment]
great! I will take care of the install issue here (#85)
